# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OyBY6ptSGehwOx38TwPN-IVxyHsJWyGT

# Assignment Code: DS-AG-032

# LLMs and LangChain Framework Assignment

# Question 1: What are Large Language Models (LLMs) and how do they function?
# Answer:

Large Language Models (LLMs) are advanced artificial intelligence systems trained on massive amounts of text data to understand, generate, summarize, translate, and answer questions in natural language. They are based on deep learning architectures, primarily the Transformer architecture, which enables them to process and understand context within large text sequences.

How LLMs Function
Data Collection
LLMs are trained using large datasets containing books, articles, websites, research papers, and other textual sources.

Tokenization
Text is broken into smaller units called tokens (words, subwords, or characters).

Training Process
The model learns patterns by predicting the next token in a sequence.
Billions of parameters are adjusted through optimization techniques.

Transformer Architecture
Uses self-attention mechanisms to understand relationships between words.
Captures long-range dependencies in text.

Inference
When a user provides a prompt, the model predicts the most probable sequence of words to generate a response.

# Examples of LLMs

GPT-4 and GPT-5

Gemini

Claude

LLaMA

Mistral

# Applications

Chatbots

Content generation

Code generation

Language translation

Document summarization

Question answering

# Question 2: Discuss the impact of LLMs on traditional software development approaches.
# Answer:

LLMs have significantly transformed traditional software development practices by automating many tasks that previously required manual effort.

Positive Impacts
1. Faster Development

Developers can generate code snippets, functions, and boilerplate code quickly.

2. Improved Productivity

Tools like GitHub Copilot assist developers during coding, reducing development time.

3. Automated Documentation

LLMs can generate:

API documentation
Technical reports
User manuals
4. Enhanced Testing

They help create:

Unit tests
Integration tests
Test cases
5. Natural Language Programming

Users can describe requirements in plain language and receive executable code.

Challenges
1. Code Quality Concerns

Generated code may contain:

Bugs
Security vulnerabilities
Inefficient logic
2. Reduced Understanding

Over-reliance may reduce developers’ understanding of underlying systems.

3. Data Privacy Issues

Sensitive information may be exposed when using cloud-based AI tools.

4. Hallucinations

LLMs may generate incorrect or non-existent APIs and functions.

Conclusion

LLMs act as powerful development assistants, increasing efficiency while still requiring human oversight.

# Question 3: What are the key advantages and limitations of using LLMs in real-world applications?
# Answer:
Advantages
1. Natural Language Understanding

LLMs can understand and generate human-like text.

2. Scalability

Can handle millions of user interactions simultaneously.

3. Automation

Automates:

Customer support
Content generation
Data analysis
4. Multilingual Support

Many LLMs support multiple languages.

5. Knowledge Extraction

Can summarize and retrieve information from large datasets.

Limitations
1. Hallucinations

May generate incorrect information confidently.

2. High Computational Cost

Training and deployment require significant hardware resources.

3. Bias

Models may inherit biases from training data.

4. Lack of Real-Time Knowledge

Without external tools, models may not know recent events.

5. Security Risks

Prompt injection and data leakage can occur.

Summary

LLMs provide significant benefits but require safeguards to ensure accuracy, privacy, and reliability.

# Question 4: Describe how different industries are being transformed by the use of LLMs. Provide examples.
# Answer:

LLMs are transforming multiple industries by improving automation, decision-making, and customer experiences.

# Healthcare

Applications:

Medical record summarization
Clinical decision support
Patient chatbots

Example:
AI assistants summarize patient histories for doctors.

# Finance

Applications:

Fraud detection
Financial analysis
Customer support

Example:
Banks use AI chatbots to answer customer inquiries.

# Education

Applications:

Personalized tutoring
Automated grading
Content creation

Example:
Students receive instant explanations for complex topics.

# Legal Industry

Applications:

Contract review
Legal research
Document summarization

Example:
Law firms use AI to identify relevant case precedents.

# E-Commerce

Applications:

Product recommendations
Customer support
Review analysis

Example:
Online stores provide AI-powered shopping assistants.

# Software Development

Applications:

Code generation
Bug fixing
Documentation

Example:
GitHub Copilot assists programmers while coding.

Conclusion

LLMs are improving productivity, reducing costs, and enabling intelligent automation across industries.

Question 5: Compare and contrast LangChain and LlamaIndex. What unique problems does each solve?
Answer:
## Answer:

| Feature           | LangChain                   | LlamaIndex                       |
| :---------------- | :-------------------------- | :------------------------------- |
| Primary Purpose   | Application orchestration  | Data indexing and retrieval      |
| Focus             | Building LLM workflows      | Connecting private data to LLMs  |
| Components        | Chains, Agents, Tools, Memory | Indexes, Retrievers, Query Engines |
| Best Use Case     | AI agents and workflow automation | Document search and retrieval    |
| Integration       | APIs, databases, tools      | Documents, PDFs, databases       |

### LangChain

LangChain helps developers build applications around LLMs by providing:

*   Prompt management
*   Agents
*   Memory
*   Tool integration
*   Workflow orchestration

**Example:** Building an AI assistant that can search the web and answer questions.

### LlamaIndex

LlamaIndex focuses on:

*   Data ingestion
*   Index creation
*   Semantic search
*   Retrieval-Augmented Generation (RAG)

**Example:** Searching thousands of PDF documents efficiently.

### Summary

*   **LangChain** = Workflow and Agent Framework
*   **LlamaIndex** = Data Retrieval Framework

They are often used together in production systems.
```

### Question 6: Implement a basic LangChain pipeline using Groq (OpenAI alternative) to answer questions based on a user input prompt.
"""

!pip install -q langchain langchain-core langchain-groq

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

# Ensure langchain-groq is installed for this cell
!pip install -q langchain-groq

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate

# Configuration specific to this cell for Q6
GROQ_KEY = "gsk_****"
MODEL = "openai/gpt-oss-120b"

# Initialize ChatGroq LLM for this pipeline
llm_groq_q6 = ChatGroq(
    model_name=MODEL,
    groq_api_key=GROQ_KEY
)

prompt = ChatPromptTemplate.from_template(
    "Answer the following question: {question}"
)

# Create the chain using the specific LLM for Q6
chain_q6 = prompt | llm_groq_q6

# Example usage for Question 6
question_text = "What is the main purpose of LangChain in LLM application development?"
response = chain_q6.invoke({"question": question_text})

print(f"Question: {question_text}")
print(f"Answer: {response.content}")

"""Question 7: Integrate LangChain with a third-party API (e.g., weather, news) and show how responses can be generated via LLMs."""

import requests
from langchain_groq import ChatGroq

WEATHER_API_KEY = "9e1e7****"
city = "Mumbai"

llm = ChatGroq(
    model="llama-3.1-8b-instant",
    groq_api_key=GROQ_KEY
)

try:
    url = f"http://api.weatherapi.com/v1/current.json?key={WEATHER_API_KEY}&q={city}"

    data = requests.get(url).json()

    if "current" in data:
        temperature = data["current"]["temp_c"]
        description = data["current"]["condition"]["text"]
    else:
        print("API Error:", data)
        temperature = "30"
        description = "Partly Cloudy"

    prompt_text = f"""
    Weather in {city}:
    Temperature: {temperature}°C
    Condition: {description}

    Summarize this weather for a traveler.
    """

    response = llm.invoke(prompt_text)

    print(response.content)

except Exception as e:
    print("Error:", e)

"""Question 8: Create a LlamaIndex implementation that indexes a local text file and retrieves answers from it."""

# ==========================================================
# STEP 1: Install Required Libraries
# ==========================================================

!pip install -q llama-index
!pip install -q llama-index-llms-groq
!pip install -q llama-index-embeddings-huggingface


# ==========================================================
# STEP 2: Create sample.txt
# ==========================================================

sample_text = """
LlamaIndex is a framework that connects Large Language Models (LLMs)
with external data sources.

It provides tools for document loading, indexing, retrieval, and querying.

Groq is a high-performance AI inference platform that enables fast execution
of large language models such as Llama 3.

Retrieval-Augmented Generation (RAG) is a technique that combines
information retrieval with language generation.

The RAG workflow consists of:

1. Loading documents
2. Creating embeddings
3. Building an index
4. Retrieving relevant information
5. Generating answers using an LLM

Benefits of LlamaIndex:

- Easy document ingestion
- Efficient retrieval
- Supports multiple vector databases
- Simplifies AI application development

LlamaIndex and Groq can be used together to create fast and scalable
question-answering systems.
"""

with open("sample.txt", "w") as f:
    f.write(sample_text)

print("sample.txt created successfully!")


# ==========================================================
# STEP 3: Import Libraries
# ==========================================================

import os
from getpass import getpass

from llama_index.core import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    Settings
)

from llama_index.llms.groq import Groq
from llama_index.embeddings.huggingface import HuggingFaceEmbedding


# ==========================================================
# STEP 4: Enter Groq API Key
# ==========================================================

groq_api_key = getpass("Enter your Groq API Key: ")

os.environ["GROQ_API_KEY"] = groq_api_key


# ==========================================================
# STEP 5: Configure Groq LLM
# ==========================================================

Settings.llm = Groq(
    model="llama-3.3-70b-versatile",
    api_key=groq_api_key
)


# ==========================================================
# STEP 6: Configure Embedding Model
# ==========================================================

Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5"
)


# ==========================================================
# STEP 7: Load Document
# ==========================================================

documents = SimpleDirectoryReader(
    input_files=["sample.txt"]
).load_data()

print(f"Documents Loaded: {len(documents)}")


# ==========================================================
# STEP 8: Create Vector Index
# ==========================================================

index = VectorStoreIndex.from_documents(documents)

print("Index created successfully!")


# ==========================================================
# STEP 9: Create Query Engine
# ==========================================================

query_engine = index.as_query_engine()


# ==========================================================
# STEP 10: Ask Questions
# ==========================================================

questions = [
    "What is LlamaIndex?",
    "What is Groq?",
    "Explain the RAG workflow.",
    "What are the benefits of LlamaIndex?"
]

for question in questions:

    response = query_engine.query(question)

    print("\n" + "="*60)
    print("Question:")
    print(question)

    print("\nAnswer:")
    print(response)

"""Question 9: Demonstrate combining LangChain with LlamaIndex to create a simple document-based Q&A chatbot."""

# ==========================
# INSTALL DEPENDENCIES
# ==========================

!pip install -q llama-index==0.14.16
!pip install -q llama-index-llms-groq==0.5.0
!pip install -q llama-index-embeddings-huggingface==0.6.1
!pip install -q langchain==0.3.27
!pip install -q langchain-core==0.3.75

# ==========================
# CREATE SAMPLE DOCUMENT
# ==========================

sample_text = """
LangChain is an open-source framework used to build applications powered by Large Language Models.

LlamaIndex is a framework that connects external data sources with Large Language Models.
It provides document loading, indexing, retrieval, and querying capabilities.

Groq is a high-performance AI inference platform that enables ultra-fast execution of Large Language Models such as Llama 3.

A document-based chatbot retrieves information from documents and answers user questions based on document content.

Retrieval-Augmented Generation (RAG) combines information retrieval with language generation.

Benefits of RAG:
1. Reduces hallucinations.
2. Improves answer accuracy.
3. Uses external knowledge.
4. Provides context-aware responses.

LangChain manages chatbot workflows.
LlamaIndex manages document retrieval.
Groq generates final answers.
"""

with open("sample.txt", "w") as f:
    f.write(sample_text)

print("sample.txt created successfully.")

# ==========================
# IMPORT LIBRARIES
# ==========================

import os
from getpass import getpass

from llama_index.core import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    Settings
)

from llama_index.llms.groq import Groq
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

from langchain_core.runnables import RunnableLambda

# ==========================
# ENTER GROQ API KEY
# ==========================

groq_api_key = getpass("Enter your Groq API Key: ")

os.environ["GROQ_API_KEY"] = groq_api_key

# ==========================
# CONFIGURE GROQ MODEL
# ==========================

Settings.llm = Groq(
    model="llama-3.3-70b-versatile",
    api_key=groq_api_key
)

# ==========================
# CONFIGURE EMBEDDINGS
# ==========================

Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5"
)

print("Models loaded successfully.")

# ==========================
# LOAD DOCUMENT
# ==========================

documents = SimpleDirectoryReader(
    input_files=["sample.txt"]
).load_data()

print(f"Loaded {len(documents)} document(s).")

# ==========================
# CREATE VECTOR INDEX
# ==========================

index = VectorStoreIndex.from_documents(documents)

query_engine = index.as_query_engine()

print("Vector index created successfully.")

# ==========================
# LANGCHAIN + LLAMAINDEX
# ==========================

def ask_document(question):
    response = query_engine.query(question)
    return str(response)

chatbot = RunnableLambda(ask_document)

print("LangChain and LlamaIndex integrated successfully.")

# ==========================
# SAMPLE QUESTIONS
# ==========================

sample_questions = [
    "What is LangChain?",
    "What is LlamaIndex?",
    "What is RAG?"
]

print("\nSample Outputs")
print("=" * 60)

for q in sample_questions:
    print(f"\nQuestion: {q}")
    print("Answer:", chatbot.invoke(q))

# ==========================
# INTERACTIVE CHATBOT
# ==========================

print("\n" + "=" * 60)
print("DOCUMENT-BASED Q&A CHATBOT")
print("=" * 60)

question_count = 1

while True:

    print(f"\nQuestion {question_count}")

    question = input("You: ")

    answer = chatbot.invoke(question)

    print("\nChatbot:", answer)

    choice = input(
        "\nDo you want to ask another question? (yes/no): "
    ).strip().lower()

    if choice != "yes":
        print("\nThank you for using the chatbot.")
        break

    question_count += 1

"""Question 10: A legal firm wants to use AI to summarize large volumes of legal documents and retrieve relevant information quickly. Propose a solution using LangChain and LlamaIndex, and explain how it would work in practice.

Answer:
Proposed Solution

A Retrieval-Augmented Generation (RAG) system combining LangChain and LlamaIndex can efficiently process legal documents.

Architecture
Document Ingestion
Document Indexing
Semantic Search
Retrieval
LLM-Based Summarization
User Query Interface
Workflow
Step 1: Document Upload

Lawyers upload:

Contracts
Case files
Legal opinions
Court judgments
Step 2: Indexing with LlamaIndex

Documents are:

Parsed
Chunked
Embedded
Stored in a vector database
Step 3: Query Processing

Users ask questions such as:

What are the termination clauses in Contract A?
Step 4: Retrieval

LlamaIndex retrieves relevant document sections.

Step 5: Response Generation

LangChain sends retrieved context to the LLM.

The LLM generates:

Summaries
Explanations
Answers
Python Code
"""

from llama_index.core import VectorStoreIndex, SimpleDirectoryReader

# Question 10 Implementation
os.makedirs('legal_docs', exist_ok=True)
with open('legal_docs/contract.txt', 'w') as f:
    f.write('Termination: 30 days notice.')

try:
    docs = SimpleDirectoryReader('legal_docs').load_data()
    index = VectorStoreIndex.from_documents(docs)
    query_engine = index.as_query_engine()
    response = query_engine.query("Summarize the termination notice.")
    print(response)
except Exception as e:
    print(f"Error in Q10: {e}")

